import type { Metadata } from "next";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { inter } from "@/common/styles/font";
import "../globals.css";
import { notFound } from "next/navigation";

import { routing } from "@/i18n/routing";
import { getMessages, setRequestLocale } from "next-intl/server";

export const metadata: Metadata = {
     title: "Create Next App",
     description: "Generated by create next app",
};

interface RootLayoutProps {
     children: React.ReactNode;
     params: Promise<{ locale: string }>;
}

const RootLayout = async ({ children, params }: RootLayoutProps) => {
     const { locale } = await params;

     if (!hasLocale(routing.locales, locale)) {
          notFound();
     }

     setRequestLocale(locale);

     // const messages = await getMessages();
     // const session = await getServerSession();

     return (
          <html lang={locale} suppressHydrationWarning={true}>
               <body className={inter.className}>{children}</body>
          </html>
     );
};

export default RootLayout;
